### ISSUE TITLE
openSMB2 resources tracking

### ISSUE THREAD

**Issue by Matriks404** [Matriks404/openSMB2#14]
* [ ] Worlds
  * [ ] World 1
    * [ ] Level 1
      * [ ] Area 0 (only tiles)
      * [ ] Area 1 (only tiles)
      * [ ] Area 2
      * [ ] Area 3
      * [ ] Area 4
    * [ ] Level 2
      * [ ] Area 0
      * [ ] Area 1
      * [ ] Area 2
      * [ ] Area 3
      * [ ] Area 4
    * [ ] Level 3
  * [ ] World 2
    * [ ] Level 1
    * [ ] Level 2
    * [ ] Level 3
  * [ ] World 3
    * [ ] Level 1
    * [ ] Level 2
    * [ ] Level 3
  * [ ] World 4
    * [ ] Level 1
    * [ ] Level 2
    * [ ] Level 3
  * [ ] World 5
    * [ ] Level 1
    * [ ] Level 2
    * [ ] Level 3
  * [ ] World 6
    * [ ] Level 1
    * [ ] Level 2
    * [ ] Level 3
  * [ ] World 7
    * [ ] Level 1
    * [ ] Level 2

* [ ] Tilemap (partial)

* [ ] Sounds and music (partial)

**Comment by Matriks404** [comment]
NOTE: This issue is a bit redundant if we close #18.

**Comment by Matriks404** [comment]
This issue is redundant and not directly related to openSMB2, closing.
