### ISSUE TITLE
1.0 Roadmap

### ISSUE THREAD

**Issue by Matriks404** [Matriks404/openSMB2#3]
* [ ] Finish map editor
* [ ] Gameplay stuff
  * [ ] Load area in memory
  * [ ] Make physics work
  * [ ] Draw objects/landscape
  * [ ] Draw entities (characters, monsters, items etc.)
* [ ] Add all levels and their resources
  * [ ] World 1
  * [ ] World 2
  * [ ] World 3
  * [ ] World 4
  * [ ] World 5
  * [ ] World 6
  * [ ] World 7
